#!/usr/bin/env bash
# Gracefully reloads Gunicorn.
# Get the process ID (PID) of the Gunicorn process
PID=$(pgrep gunicorn)

if [[ -z $PID ]]; then
  echo "Gunicorn is not currently running."
  exit 1
fi

echo "Reloading Gunicorn gracefully..."

# Send the HUP signal to the Gunicorn process
kill -HUP $PID

echo "Gunicorn reloaded."
